### ISSUE TITLE
安装失败，Failed to write configuration: /proc/net/appex/wanKbps

### ISSUE THREAD

**Issue by AdiEcho** [fei5seven/lotServer#1]
![image](https://user-images.githubusercontent.com/30563671/65900498-b6c82a80-e3e8-11e9-94a2-e284b81038e1.png)
这是用的大佬的脚本
![image](https://user-images.githubusercontent.com/30563671/65900598-ef680400-e3e8-11e9-9fdb-347cc8c3e6d9.png)
zhe'shi
这是用的萌咖大佬的脚本，这个貌似安装成功，但是`tcp-segmentation-offload: off
	tx-tcp-segmentation: off [requested on]
	tx-tcp6-segmentation: off [requested on]
generic-segmentation-offload: off [requested on]
`这几行的requested on 让我感觉应该是没有成功，请教一下大佬该如何解决。

**Comment by fei5seven** [comment]
那个我给关掉了 没用而且想改回去还特别麻烦 开了这几个你如果想用bbr都不起作用了
