### ISSUE TITLE
Error! I can not generate the Lic for you, Please try again later. 

### ISSUE THREAD

**Issue by 1265578519** [fei5seven/lotServer#10]
Error! I can not generate the Lic for you, Please try again later. 

这个错误是咋回事啊

**Comment by 1265578519** [comment]
装不上了啊，十多天了，怎么还没修复呢，能不能把服务器文件发我一份呢？我放自己服务器上

**Comment by fei5seven** [comment]
又一个不看简介的。许可生成有开源文件.https://github.com/Tai7sy/LotServer_KeyGen
另外我想了一下还是方便一下大众吧...然后后台偷窥你们的IP和mac(((((((((((
