### ISSUE TITLE
大佬你的脚本过完今年圣诞还能用吗

### ISSUE THREAD

**Issue by ghost** [fei5seven/lotServer#12]
2021 12 25以后还能用吗？

**Comment by dgfrwx** [comment]
![Uploading IMG_20210407_130517.JPG…]()

**Comment by earth-5G** [comment]
我也是有这个问题，我也是今天重装才意识到这个问题！！希望重装一下就能解决！

**Comment by fei5seven** [comment]
防机场用的。到期一个月左右的时候就改日期，建议还是自建api获取证书

**Comment by earth-5G** [comment]
> 防机场用的。到期一个月左右的时候就改日期，建议还是自建api获取证书

关键是不会自建api，大佬会处理就好了！

**Comment by leo985** [comment]
现在过期时间是6月30号，到期了有什么方法？

**Comment by fei5seven** [comment]
> > 防机场用的。到期一个月左右的时候就改日期，建议还是自建api获取证书
>

> 现在过期时间是6月30号，到期了有什么方法？

https://github.com/fei5seven/lotServer/issues/12#issuecomment-963984163
