### ISSUE TITLE
旧配置

### ISSUE THREAD

**Issue by LexterS999** [fei5seven/lotServer#13]
我想使用放在这里的配置https://github.com/fei5seven/lotServer/blob/master/lotServer/apxfiles/etc/config，但系统给我配置了另一个这样的配置https://github.com/fei5seven/lotServer/blob/master/lotServer/apxfiles/bin/lotServer.sh。当我试图替换它时，LotServer停止了工作。如何让它变得正确？

**Comment by fei5seven** [comment]
实际上只是修改了部分设置。当然具体我也没管过这些东西，也不建议在做什么修改（毕竟我也就是精神继承人而已）
