### ISSUE TITLE
大佬你这个脚本是自动配置好参数， 然后永久授权的是么

### ISSUE THREAD

**Issue by Ro0kie** [fei5seven/lotServer#2]
大佬你这个脚本是自动配置好参数， 然后永久授权的是么

**Comment by fei5seven** [comment]
是，基本开箱食用，授权我改成9999年了。主要是会有概率让机器宕机，还是没找到原因，aws gce ali这些共享CPU的都没事，独立虚拟CPU都有概率死机、
