### ISSUE TITLE
有关于debian9

### ISSUE THREAD

**Issue by Sutodonez** [fei5seven/lotServer#3]
目前只找到了大佬fork的这个版本可以正常在debian9 4.9.0-4上安装，原本使用的脚本都开始报内核版本不支持……莫非是其他最新版的源都被干掉了吗（惊）

**Comment by fei5seven** [comment]
应该没有吧。。。很久都不更新了。个人还是推荐用centos7，稳一点还省资源

**Comment by fei5seven** [comment]
其他版本吧。。。获取激活证书的连接指向的还是萌咖大佬的api，然后他的api早就关了吧？=，=我是改成我自己的api了所以能玩。不然我为什么说我也就会个修修补补外加一个fork呢（笑）
