### ISSUE TITLE
vicer api接口挂了 麻烦看看

### ISSUE THREAD

**Issue by Meilinhost** [fei5seven/lotServer#7]
lotServer/
lotServer/apxfiles/
lotServer/install.sh
lotServer/apxfiles/bin/
lotServer/apxfiles/etc/
lotServer/apxfiles/bin/lotServer.sh
lotServer/apxfiles/bin/setConfig.sh
lotServer/apxfiles/bin/showConfig.sh
lotServer/apxfiles/bin/utils.sh
lotServer/apxfiles/etc/config
lotServer has been removed! 
Error! I can not generate the Lic for you, Please try again later.

**Comment by fei5seven** [comment]
需要自己搭建。授权也不是vicer的
